### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'end' on 'TimeRanges'

### ISSUE THREAD

**Issue by aktary** [2013gang/angular-video-background#3]
I implemented your demo code and got the following cryptic error.  FWIW, it appears to work (the video shows up and plays), but I'm getting this error in the console:

Uncaught IndexSizeError: Failed to execute 'end' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0).(anonymous function) @ vidBg.min.js:1eventHandler @ angular.js:3032

**Comment by aktary** [comment]
Clarification: I used the demo code in the readme, not the demo.html (didn't notice it till just now).

**Comment by 2013gang** [comment]
sorry for late reply  (just back from a long vacation :)

I will try it in a couple of days. Meanwhile, please refer to demo/index.html, because readMe and the demo website may be out-dated.

Thanks

**Comment by NetanelBasal** [comment]
I am getting this error too, even when i copied the demo.html example,  did you found what is the problem?

**Comment by 2013gang** [comment]
should now be fixed. [ref](http://stackoverflow.com/questions/25651719/why-does-audio-buffered-end0-get-an-error-message-when-i-try-to-get-buffered-t)
