### ISSUE TITLE
remove lodash

### ISSUE THREAD

**Issue by heavysixer** [2013gang/angular-video-background#7]
It looks like you are only using lowdash for `_.each` and `_.isArray`.  Both of these methods have polyfills directly from within Angular core. Would you consider removing these methods for:

`angular.forEach`
https://docs.angularjs.org/api/ng/function/angular.forEach

`angular.isArray`
https://docs.angularjs.org/api/ng/function/angular.isArray

I don't develop with CoffeeScript otherwise I would provide pull request.

Best Regards,
Mark

**Comment by 2013gang** [comment]
totally. Will do it in a couple of days

Thanks for the suggestion

**Comment by heavysixer** [comment]
I created a pull request for you, and also cleaned up a couple of issues in the gulp file that were preventing me from getting a good build.

**Comment by 2013gang** [comment]
Thanks!

**Comment by heavysixer** [comment]
cool would you mind doing a new release so that i can use it in my code? :-) Thanks!

**Comment by 2013gang** [comment]
done
